name: Debug Build

# 触发器
on:
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Debug Build Title"
        required: true
        default: "SmsForwarder"

jobs:
  debug_build:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/debug" # 调整为 debug 输出目录

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 设置 JDK 环境
      - name: Set Up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      # 添加测试密钥签名
      - name: Add Test Keystore
        run: |
          mkdir -p ${HOME}/.android
          echo -e "-----BEGIN CERTIFICATE-----\n<Your Test Certificate>\n-----END CERTIFICATE-----" > ${HOME}/.android/debug.keystore
          echo -e "androiddebugkey\nandroid\nandroid\n" > ${HOME}/.android/debug.keystore.password

      # 打包 Debug 版本
      - name: Build Debug APK
        run: bash ./gradlew assembleDebug

      # 存档打包的文件，以便后续上传
      - name: Upload Debug APK to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "SmsF_debug.apk"
          path: "${{ env.output }}/app-debug.apk"
